
package com.record.tcgl.webservice.JobList;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */


import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 3.4.0
 * 2020-09-24T11:02:10.417+08:00
 * Generated source version: 3.4.0
 *
 */
public final class JobListService_JobListServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://webservice.tcgl.record.com", "JobListServiceImplService");

    private JobListService_JobListServicePort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = JobListServiceImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        JobListServiceImplService ss = new JobListServiceImplService(wsdlURL, SERVICE_NAME);
        JobListService port = ss.getJobListServicePort();

        {
        System.out.println("Invoking getUserInfo...");
        String _getUserInfo_userName = "";
        String _getUserInfo__return = port.getUserInfo(_getUserInfo_userName);
        System.out.println("getUserInfo.result=" + _getUserInfo__return);


        }

        System.exit(0);
    }

}
