
package com.record.tcgl.webservice.JobList;


import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.4.0
 * 2020-09-24T11:02:10.469+08:00
 * Generated source version: 3.4.0
 *
 */

public class JobListService_JobListServicePort_Server{

    protected JobListService_JobListServicePort_Server() throws Exception {
        System.out.println("Starting Server");
        Object implementor = new JobListServicePortImpl();
        String address = "http://127.0.0.1:8099/jobList/JobListService";
        Endpoint.publish(address, implementor);
    }

    public static void main(String args[]) throws Exception {
        new JobListService_JobListServicePort_Server();
        System.out.println("Server ready...");

        Thread.sleep(5 * 60 * 1000);
        System.out.println("Server exiting");
        System.exit(0);
    }
}
