package com.record.tcgl.webservice;


import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.4.0
 * 2020-09-24T11:02:10.460+08:00
 * Generated source version: 3.4.0
 *
 */
@WebService(targetNamespace = "http://webservice.tcgl.record.com", name = "JobListService")
@XmlSeeAlso({ObjectFactory.class})
public interface JobListService {

    @WebMethod
    @RequestWrapper(localName = "getUserInfo", targetNamespace = "http://webservice.tcgl.record.com", className = "com.record.tcgl.GetUserInfo")
    @ResponseWrapper(localName = "getUserInfoResponse", targetNamespace = "http://webservice.tcgl.record.com", className = "com.record.tcgl.GetUserInfoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String getUserInfo(

        @WebParam(name = "userName", targetNamespace = "")
        String userName
    );
}
