
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.record.tcgl.webservice;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.4.0
 * 2020-09-24T11:02:10.442+08:00
 * Generated source version: 3.4.0
 *
 */

@WebService(
                      serviceName = "JobListServiceImplService",
                      portName = "JobListServicePort",
                      targetNamespace = "http://webservice.tcgl.record.com",
                      wsdlLocation = "file:/C:/Users/SHUGUA~1/AppData/Local/Temp/tempdir7063548127181534198.tmp/JobListService_1.wsdl",
                      endpointInterface = "com.record.tcgl.webservice.JobListService")

public class JobListServicePortImpl implements JobListService {

    private static final Logger LOG = Logger.getLogger(JobListServicePortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.record.tcgl.JobListService#getUserInfo(java.lang.String userName)*
     */
    @Override
    public String getUserInfo(String userName) {
        LOG.info("Executing operation getUserInfo");
        System.out.println(userName);
        try {
            String _return = "";
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
