package com.record.tcgl.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.4.0
 * 2020-09-24T11:02:10.479+08:00
 * Generated source version: 3.4.0
 *
 */
@WebServiceClient(name = "JobListServiceImplService",
                  wsdlLocation = "file:/C:/Users/SHUGUA~1/AppData/Local/Temp/tempdir7063548127181534198.tmp/JobListService_1.wsdl",
                  targetNamespace = "http://webservice.tcgl.record.com")
public class JobListServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://webservice.tcgl.record.com", "JobListServiceImplService");
    public final static QName JobListServicePort = new QName("http://webservice.tcgl.record.com", "JobListServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/SHUGUA~1/AppData/Local/Temp/tempdir7063548127181534198.tmp/JobListService_1.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(JobListServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/SHUGUA~1/AppData/Local/Temp/tempdir7063548127181534198.tmp/JobListService_1.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public JobListServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public JobListServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public JobListServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public JobListServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public JobListServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public JobListServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns JobListService
     */
    @WebEndpoint(name = "JobListServicePort")
    public JobListService getJobListServicePort() {
        return super.getPort(JobListServicePort, JobListService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns JobListService
     */
    @WebEndpoint(name = "JobListServicePort")
    public JobListService getJobListServicePort(WebServiceFeature... features) {
        return super.getPort(JobListServicePort, JobListService.class, features);
    }

}
